version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web