version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8 --limit-max-requests 3000 --limit-concurrency 3000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web